name: Build, Test and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build and test with Maven
        run: mvn clean verify

      - name: Qodana Code Analysis
        uses: JetBrains/qodana-action@v2025.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

      - name: Upload test reports
        uses: actions/upload-artifact@v4  # CAMBIADO DE v3 A v4
        with:
          name: test-reports
          path: |
            target/site/jacoco/
            target/surefire-reports/

  deploy:
    runs-on: ubuntu-latest
    needs: quality-check
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3  # ACTUALIZADO A LA VERSIÓN MÁS RECIENTE
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 -t julian54628/sirhaexodo:latest .
          docker push julian54628/sirhaexodo:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SIRHA-EXODO'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'julian54628/sirhaexodo:latest'